name: Flutter CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Keranjang Repository
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7' 

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🧪 Run Tests
        run: flutter test
        continue-on-error: true

      - name: 🏗️ Build APK
        run: flutter build apk --release

      - name: 📤 Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: 🚀 Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📢 Notify Telegram (Success)
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Build APK berhasil untuk commit ${{ github.sha }}"

      - name: ❌ Notify Telegram (Failed)
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ Build gagal di workflow GitHub Actions"

      - name: 🔨 Build Split APK
        run: flutter build apk --split-per-abi


      - name: 📤 Send APKs to Telegram
        if: success()
        run: |
          for file in build/app/outputs/flutter-apk/*.apk; do
            curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument \
            -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -F document=@$file \
            -F caption="📦 $(basename $file) berhasil di-build 🚀"
          done

      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}